"""CV screening / candidate schemas."""
from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class CandidateCreateMeta(BaseModel):
    full_name: str | None = None
    email: str | None = None
    phone: str | None = None


class CandidateUpdate(BaseModel):
    full_name: str | None = None
    email: str | None = None
    phone: str | None = None
    parsed_data: dict[str, Any] | None = None
    status: Literal["uploaded", "parsed", "scored", "shortlisted", "rejected", "hired"] | None = None


class CandidateRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    job_description_id: int | None
    full_name: str | None
    email: str | None
    phone: str | None
    cv_file_path: str
    parsed_data: dict[str, Any] | None
    status: str
    source: str = "manual"
    source_ref: str | None = None
    match_confidence: float | None = None
    match_reasoning: str | None = None
    submitted_at: datetime | None = None
    created_at: datetime
    updated_at: datetime


class CandidateScoreRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    candidate_id: int
    scoring_criteria_id: int
    raw_score: float | None
    notes: str | None


class CandidateRankingRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    job_description_id: int
    candidate_id: int
    total_score: float
    rank_position: int
    computed_at: datetime


class RankingRow(BaseModel):
    candidate_id: int
    full_name: str | None
    email: str | None
    status: str
    total_score: float
    rank_position: int
    pending_manual_review: bool = False


class ScoreOverrideRequest(BaseModel):
    scoring_criteria_id: int
    raw_score: float
    reason: str = Field(min_length=3)


class SkillEvaluationRow(BaseModel):
    skill: str
    required_level: float
    matched: bool
    raw_score: float | None
    max_points: float
    notes: str | None


class CandidateEvaluation(BaseModel):
    candidate_id: int
    job_description_id: int
    job_title: str
    overall_score: float | None
    rank_position: int | None
    rating_out_of_10: float | None = None
    recommendation: Literal["shortlist", "consider", "reject"]
    recommendation_label: str
    summary: str
    why_accepted: str = ""
    why_rejected: str = ""
    strengths: list[str]
    gaps: list[str]
    skills: list[SkillEvaluationRow]


class HireRequest(BaseModel):
    employee_code: str
    department_id: int
    role_title: str | None = None
    base_salary: float | None = None
    date_joined: str | None = None  # ISO date


class CvSourceResult(BaseModel):
    source: Literal["webmail", "outlook", "whatsapp", "gmail", "google_form"]
    configured: bool
    fetched: int
    message: str | None = None


class CvDuplicateCandidateRead(BaseModel):
    """A fetched CV that was not imported because a candidate with the same
    source_ref already exists.

    source_ref is generated by each source:
    - webmail: Message-ID (or imap-uid-*)
    - google_form: form_row_N

    This is intentionally *not* keyed by the applicant email, because the
    same person can apply to multiple roles. Admins need visibility and can
    decide how to handle the existing candidate record."""

    source: str
    source_ref: str

    existing_candidate_id: int
    existing_job_description_id: int | None
    existing_status: str

    existing_full_name: str | None = None
    existing_email: str | None = None

    submitted_full_name: str | None = None
    submitted_email: str | None = None


class CvSyncResult(BaseModel):
    sources: list[CvSourceResult]
    total_fetched: int
    auto_matched: int
    unassigned: int
    duplicates_skipped: int
    restored_files: int = 0
    duplicates: list[CvDuplicateCandidateRead] = []
    candidates: list[CandidateRead]


class CandidateAssignRequest(BaseModel):
    job_description_id: int
